POST http://localhost:8080/videos
Content-Type: application/json

{
    "title": "videos 02",
    "description": "Esse é o video 02",
    "duration": 60
}


###

POST http://localhost:8080/auth/register/
Content-Type: application/json

{
    "cpf": "02073347678",
    "nome_completo": "Maria Faustino Santos",
    "data_nasc": "18/12/1996",
    "celular": "(11)000000000",
    "email": "Fawwiaaa32@yahoo.com",
    "username": "teste",
    "senha": "testeR",
    "cep": "0820045",
    "endereco": "Rua: Yudá do Ó",
    "numero": "1545",
    "bairro": "JD helena",
    "cidade": "São Paulo",
    "uf": "SP"
}


###

POST http://localhost:8080/resgister/category/
Content-Type: application/json

{
    "id_cat": 2,
    "descricao": "Sala"
}

###

POST http://localhost:8080/resgister/product/
Content-Type: application/json

{
    "id_prod": 2,
    "nome_prod": "Kit de panelas antiaderente cor vermelha",
    "descricao": "Panela anteaderente",
    "classificacao": "Novo",
    "id_categoria": 1,
    "preco": "249,90",
    "qnt": 1,
    "desconto": "Sim",
    "preco_desconto":"400.00",
    "qnt_parcelas": 6,
    "valor_parcela": "41.65",
    "frete": 1,
    "valor_frete": "24.90"
}

###

POST http://localhost:8080/auth/registerUser/
Content-Type: application/json

{
    "username": "jbff",
    "senha": "faus123",
    "cpf_user": "44740347830"
}

###

###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "username": "Henrique",
    "senha": "teste"
}

###


POST http://localhost:8080/auth/registerUser/
Content-Type: application/json

{
    "cpf": "32073347678",
    "rg": "38735305x",
    "nome_completo": "Maria Faustino Santos",
    "nome_mae": "Alaide Ribeiro Faustino",
    "data_nasc": "18/12/1996",
    "celular": "(11)000000000",
    "email": "Fawwiaaa32@yahoo.com",
    "cargo": "gerente",
    "username": "Henrique",
    "senha": "teste",
    "cep": "0820045",
    "endereco": "Rua: Yudá do Ó",
    "numero": "1545",
    "bairro": "JD helena",
    "cidade": "São Paulo",
    "uf": "SP"
}


###

###
GET http://localhost:8080/videos

###

GET http://localhost:8080/products/

###

GET http://localhost:8080/registrations/

###

PUT http://localhost:8080/videos
Content-Type: application/json

{
    "title": "videos 03",
    "description": "Esse é o video 03",
    "duration": 180
}

###

DELETE http://localhost:8080/videos