POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "videos 02",
    "description": "Esse é o video 02",
    "duration": 60
}


###

POST http://localhost:3333/auth/register/
Content-Type: application/json

{
    "cpf": "02073347678",
    "nome_completo": "Maria Faustino Santos",
    "data_nasc": "18/12/1996",
    "celular": "(11)000000000",
    "email": "Fawwiaaa32@yahoo.com",
    "username": "teste",
    "senha": "testeR",
    "cep": "0820045",
    "endereco": "Rua: Yudá do Ó",
    "numero": "1545",
    "bairro": "JD helena",
    "cidade": "São Paulo",
    "uf": "SP"
}


###


POST http://localhost:3333/auth/registerUser/
Content-Type: application/json

{
    "username": "jbff",
    "senha": "faus123",
    "cpf_user": "44740347830"
}

###

GET http://localhost:3333/videos

###

GET http://localhost:3333/registrations

###

PUT http://localhost:3333/videos
Content-Type: application/json

{
    "title": "videos 03",
    "description": "Esse é o video 03",
    "duration": 180
}

###

DELETE http://localhost:3333/videos